ALTER SYSTEM SET wal_level = logical;

CREATE USER debezium_user WITH REPLICATION PASSWORD 'secret';
ALTER USER debezium_user WITH SUPERUSER;
GRANT CONNECT ON DATABASE demo TO debezium_user;

CREATE TABLE USERS
(
    ID            BIGSERIAL PRIMARY KEY,
    NAME          VARCHAR(500),
    DATE_OF_BIRTH DATE,
    PASSWORD      VARCHAR(500) CHECK (LENGTH(PASSWORD) >= 8)
);

CREATE TABLE ACCOUNT
(
    ID      BIGSERIAL PRIMARY KEY,
    USER_ID BIGINT,
    BALANCE DECIMAL,
    FOREIGN KEY (USER_ID) REFERENCES USERS (ID)
);

CREATE TABLE EMAIL_DATA
(
    ID      BIGSERIAL PRIMARY KEY,
    USER_ID BIGINT,
    EMAIL   VARCHAR(200) UNIQUE,
    FOREIGN KEY (USER_ID) REFERENCES USERS (ID)
);

CREATE TABLE PHONE_DATA
(
    ID      BIGSERIAL PRIMARY KEY,
    USER_ID BIGINT,
    PHONE   VARCHAR(13) UNIQUE,
    FOREIGN KEY (USER_ID) REFERENCES USERS (ID)
);

GRANT CREATE ON DATABASE demo TO debezium_user;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO debezium_user;

ALTER TABLE USERS REPLICA IDENTITY FULL;
ALTER TABLE EMAIL_DATA REPLICA IDENTITY FULL;
ALTER TABLE PHONE_DATA REPLICA IDENTITY FULL;

DROP PUBLICATION IF EXISTS dbz_publication;
CREATE PUBLICATION dbz_publication FOR TABLE users, email_data, phone_data;
